/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stakingPoolSol from "./StakingPool.sol";
export type { stakingPoolSol };
import type * as testTokenSol from "./TestToken.sol";
export type { testTokenSol };
export * as factories from "./factories";
export type { IERC20 } from "./StakingPool.sol/IERC20";
export { IERC20__factory } from "./factories/StakingPool.sol/IERC20__factory";
export type { StakingPool } from "./StakingPool.sol/StakingPool";
export { StakingPool__factory } from "./factories/StakingPool.sol/StakingPool__factory";
export type { IERC20Like } from "./TestToken.sol/IERC20Like";
export { IERC20Like__factory } from "./factories/TestToken.sol/IERC20Like__factory";
export type { TestToken } from "./TestToken.sol/TestToken";
export { TestToken__factory } from "./factories/TestToken.sol/TestToken__factory";
