polygon:
  amoy:
    contractAddress: "0x1a4cC30f2aA0377b0c3bc9848766D90cb4404124"
    networkURL: "https://polygon-amoy.g.alchemy.com/v2/Q-BMUJjjgQO7TqEWKhba8njT6mZRtB8T"
    defaultGasLimit: 600000
    confirmationTimeout: "10s"
    confirmationBlockCount: 5
    receiptTimeout: "600s"
    minGasPrice: 0
    maxGasPrice: 1000000
    rpcResponseTimeout: "5s"
    waitReceiptCycleTime: "30s"
    waitBlockCycleTime: "30s"
    gasLess: true
    rhsSettings:
      mode: "None"
      contractAddress: "0x16A1ae4c460C0a42f0a87e69c526c61599B28BC9"
      rhsUrl: "https://rhs-staging.polygonid.me"
    chainID: "80002"
    publishingKey: "pbkey"
