/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20Like__factory } from "./IERC20Like__factory";
export { TestToken__factory } from "./TestToken__factory";
